name: Generate sitemap.txt

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate sitemap.txt
        run: |
          echo "https://minimal-peil.github.io/" > sitemap.txt
          find ./_posts -name "*.md" | while read file; do
            filename=$(basename "$file")
            date=$(echo $filename | cut -d'-' -f1-3 | tr '-' '/')
            slug=$(echo $filename | cut -d'-' -f4- | sed 's/.md//')
            echo "https://minimal-peil.github.io/$date/$slug/" >> sitemap.txt
          done

      - name: Commit sitemap.txt
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'ペイルbot'
          git config --global user.email 'peil@example.com'
          git add sitemap.txt
          git commit -m "Auto-generate sitemap.txt" || echo "No changes to commit"
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }} HEAD:main --force
