name: Generate sitemap.txt

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Commit sitemap.txt
        run: |
          git config --global user.name 'ペイルbot'
          git config --global user.email 'peil@example.com'
          git add sitemap.txt
          git commit -m "Auto-generate sitemap.txt"
          git push --force
